# yml
# 야믈 (YAML)
# Spring Boot 프로젝트의 설정 파일, 애플리케이션이 실행될 때 이 파일을 읽음.
# DB 연결 정보, 서버 포트, 로깅 설정, 사용자 정의 설정 등을 적용.
spring:
  application:
    name: triplog

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe  # 본인 Oracle 설정에 맞게 수정
    username: javago
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
      # 또는 update, create 등
      # update: 누락된 컬럼이나 제약 조건을 Hibernate가 자동으로 수정하려고 시도함(개발 중엔 가능)
      # => 개발 후엔 validate나 none으로 설정해야함.
      # validate: 엔티티와 DB 테이블 구조가 다르면 애플리케이션 시작 시 에러 발생
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    # 오라클 12c 이후(18c, 19c, 21c 등)는 대부분 Oracle12cDialect 또는 OracleDialect 로 통합해서 사용
  
  # Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  # Thymeleaf cache 사용 중지 => 캐싱 기능을 false로 설정
  thymeleaf:
    cache: false

# 서버 포트 지정
server:
  port: 8085

# 결제 API키 연결
portone:
  imp-key: "5202336544001223"
  imp-secret: "ftSR1sAELSvBytxpz7B3dAk5hEOs7C1LZ9h7oqwvvirOoxi8rjtfALpV7jlRbfrQVUNygsrUcrkTqFCo"
  store-id: "store-4e640aa5-588e-43a9-acf5-ebaeff70b074"
  channel-key: "channel-key-8c3e9cfb-a553-471c-bea5-148c3270fea1"

# SQL문(DDL) 로그에 출력
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace



