# yml
# 야믈 (YAML)
# Spring Boot 프로젝트의 설정 파일, 애플리케이션이 실행될 때 이 파일을 읽음.
# DB 연결 정보, 서버 포트, 로깅 설정, 사용자 정의 설정 등을 적용.
spring:
  application:
    name: triplog

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe  # 본인 Oracle 설정에 맞게 수정
    connectionProperties: oracle.jdbc.defaultNChar=true
    username: javago
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
      # 또는 update, create 등
      # update: 누락된 컬럼이나 제약 조건을 Hibernate가 자동으로 수정하려고 시도함(개발 중엔 가능)
      # => 개발 후엔 validate나 none으로 설정해야함.
      # validate: 엔티티와 DB 테이블 구조가 다르면 애플리케이션 시작 시 에러 발생
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.OracleDialect
    # 오라클 12c 이후(18c, 19c, 21c 등)는 대부분 Oracle12cDialect 또는 OracleDialect 로 통합해서 사용
  
  # Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  # Thymeleaf cache 사용 중지 => 캐싱 기능을 false로 설정
  thymeleaf:
    cache: false

  # 스킨 업로드 이미지(.jpg, .jpeg, .png, .gif, .webp) 서버 파일 크기 제한 확장
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 서버 포트 지정
server:
  port: 8085

# 결제 API키 연결
portone:
  imp-key: "5202336544001223"
  imp-secret: "ftSR1sAELSvBytxpz7B3dAk5hEOs7C1LZ9h7oqwvvirOoxi8rjtfALpV7jlRbfrQVUNygsrUcrkTqFCo"
  store-id: "store-4e640aa5-588e-43a9-acf5-ebaeff70b074"
  channel-key: "channel-key-8c3e9cfb-a553-471c-bea5-148c3270fea1"

# 이모티콘 API키 연결
stipop:
  api-key: "d7f7de93bb1baec62995773ba0665e07"

# SQL문(DDL) 로그에 출력
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace
#    org.hibernate.orm.jdbc.bind: trace

# 초기 관리자 계정 설정
app:
  initial-admins:
    enabled: true # 초기 관리자 생성 활성화/비활성화
    accounts:
      - id: ucna
        name: 나웅채
        nickname: 루피아빠
        password: pw01
        phone: 010-0903-1001
        gender: MALE

      - id: dyshin
        name: 신동영
        nickname: 바른남자
        password: pw02
        phone: 010-0903-1002
        gender: MALE

      - id: smyu
        name: 유성민
        nickname: 취미생활만렙
        password: pw03
        phone: 010-0903-1003
        gender: MALE

      - id: mhkim
        name: 김민형
        nickname: 꽃길걸을꼬야
        password: pw04
        phone: 010-0903-1004
        gender: MALE

      - id: egsa
        name: 사은규
        nickname: 다비켜스웩
        password: pw05
        phone: 010-0903-1005
        gender: MALE